# Copyright

<PRE>
Jelen iTorch notebook a Budapesti Műszaki és Gazdaságtudományi Egyetemen tartott "Deep Learning a gyakorlatban Python és LUA alapon" tantárgy segédanyagaként készült. 
A tantárgy honlapja: http://smartlab.tmit.bme.hu/oktatas-deep-learning
Deep Learning kutatás: http://smartlab.tmit.bme.hu/deep-learning
Jelen notebook a hivatalos dokumentáció alapján készült: https://docs.scipy.org/doc/numpy-dev/user/quickstart.html

A notebook bármely részének újra felhasználása, publikálása csak a szerzők írásos beleegyezése esetén megegengedett.

2016 (c) Császár Márk, Tóth Bálint Pál (toth.b kukac tmit pont bme pont hu)
</PRE>

# Numpy csomag

A gépi tanulás és így a mély tanulás során egyik leggyakrabban alkalmazott Python csomag a Numpy, amelyet az alábbi paranccsal tudunk betölteni, majd később np-ként hivatkozni rá.

In [1]:
import numpy as np

A Numpy alapvetően homogén, egy- vagy többdimenziós mátrixok (= tömbök = tensorok) kezelésére szolgál. Ezen mátrixok elemei számok, melyek ugyanazon típusból származnak, tömbön belüli poziciójukat pedig pozitív, egész számok segítségével adhatjuk meg.

# Numpy tömbök jellemzői

Fontos, gyakran használt jellemzők:

    ndarray.ndim - A tömb dimenziója.

    ndarray.shape - A tömb formája, amely megadja a tömb méretét minden dimenzió mentén. 2 dimenziós mátrixok esetében az n sorból illetve m oszlopból mátrix alakja (n,m) lesz. 

    ndarray.size - A tömbben szereplő elemek száma, amely megegyezik az dimenziók menti méretek szorzatával. 

    ndarray.dtype - A tömbbeli elemek típusa. 

További említésre méltó jellemzők (ezeket ritkán fogjuk használni):

    ndarray.itemsize - Az egyes elemek mérete byte-okban kifejezve, összhangban az előzőleg említett típussal.

    ndarray.data - A tömb összes elemét tartalmazó buffer.


# Numpy tömbök létrehozása

Mély tanuló rendszerek szempontjából fontosabb adattípusok: 

    bool_ (pl. bináris adatok)
    
    int_ (pl. képek RGB csatornái)
    
    float_ (32 bites, általános adatok)
    
    float16_ (16 bites, half-precision, általános adatok): egyre nagyobb teret hódít előnyei miatt (gyorsabb, több fér bele a memóriába és deep learning célokra jól használható)

Hibás megoldás:

In [2]:
a = np.array(1,2,3,4)    # HIBÁS


ValueError: only 2 non-keyword arguments accepted

Helyes megoldás:

In [3]:
a = np.array([1,2,3,4])  # HELYES
a

array([1, 2, 3, 4])

Egy 3 dimenziós Numpy tömb létrehozása:

In [4]:
b = np.array([(1.5,2,3), (4,5,6)]) 
b

array([[ 1.5,  2. ,  3. ],
       [ 4. ,  5. ,  6. ]])

A tömb deklarálásakor az elemek (és így a tömb) típusát is megadhatjuk:

In [5]:
c = np.array( [ [1.2,2.3], [3.7,4.5] ], dtype=float ) 
c

array([[ 1.2,  2.3],
       [ 3.7,  4.5]])

Csupa nullákból álló 3x4-es méretű tömb létrehozása, a numpy.zeros() függvénnyel (gyakran használjuk):

In [6]:
d = np.zeros( (3,4) ) 
d

array([[ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.],
       [ 0.,  0.,  0.,  0.]])

2 darab 3x4-es méretű tömb (azaz egy 3D-s tömb) létrehozása a numpy.ones() függvénnyel, mely csupa egyest (16 bites egész számokat) tartalmaz:

In [7]:
e = np.ones( (2,3,4), dtype=np.int16 )
e

array([[[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]],

       [[1, 1, 1, 1],
        [1, 1, 1, 1],
        [1, 1, 1, 1]]], dtype=int16)

2x3-as méretű üres tömb létrehozása a numpy.empty() segítségével. Most a Jupyter Notebookban nullákat látunk, de valójában memóriacímek lesznek a tömb elemei.

In [8]:
f = np.empty( (2,3) ) 
f

array([[ 0.,  0.,  0.],
       [ 0.,  0.,  0.]])

Az első és második argumentum által határolt intervallumból a harmadik argumentum számú elemet egyenlő távolságra helyez el egymástól és ír bele egy numpy tömbbe. Sokat használjuk.

In [9]:
g = np.linspace( 0, 2, 9 )  # 0 és 2 között 9 számot generál
g

array([ 0.  ,  0.25,  0.5 ,  0.75,  1.  ,  1.25,  1.5 ,  1.75,  2.  ])

Ugyanez a függvény -2*pi és 2*pi tartományból, 15 elemmel:

In [10]:
h = np.linspace( -2*np.pi, 2*np.pi , 15 )
h

array([-6.28318531, -5.38558741, -4.48798951, -3.5903916 , -2.6927937 ,
       -1.7951958 , -0.8975979 ,  0.        ,  0.8975979 ,  1.7951958 ,
        2.6927937 ,  3.5903916 ,  4.48798951,  5.38558741,  6.28318531])

Hasonló a linspace()-hez, de akkor célszerű használni, ha a léptetési mérték egész szám. Amennyiben nem adunk meg paraméterként tartomány határokat illetve léptetést, akkor egyszerűen létre tudunk hozni egy új tömböt is, amely automatikusan feltöltésre kerül.

In [11]:
i = np.arange(15) 
i

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14])

Amennyiben túl sok tömbbeli elemet kellene megjeleníteni, akkor csak a tartományok utolsó elemei kerülnek vizualizálásra. A reshape függvény működéséről később lesz szó.

In [12]:
print(np.arange(10000).reshape(100,100)) 

[[   0    1    2 ...,   97   98   99]
 [ 100  101  102 ...,  197  198  199]
 [ 200  201  202 ...,  297  298  299]
 ..., 
 [9700 9701 9702 ..., 9797 9798 9799]
 [9800 9801 9802 ..., 9897 9898 9899]
 [9900 9901 9902 ..., 9997 9998 9999]]


# Elemi műveletek

"a" tömb létrehozása:

In [13]:
a = np.array( [20,30,40,50] ) 
a

array([20, 30, 40, 50])

"b" tömb létrehozása

In [14]:
b = np.arange( 4 ) 
b

array([0, 1, 2, 3])

Elemenkénti kivonás:

In [15]:
c = a-b 
c

array([20, 29, 38, 47])

"b" tömb elemeinek négyzete:

In [16]:
b**2 

array([0, 1, 4, 9])

A tömb elemeinek 10*sinus értékeinek kiszámítása. A Numpy függvények esetében elég csak a tömböt magát átadni a függvénynek. Nincs szükség arra, hogy végigiteráljunk az összes elemen.

In [17]:
10*np.sin(a) 

array([ 9.12945251, -9.88031624,  7.4511316 , -2.62374854])

Feltétel teljesülésének ellenőrzése és "boole" tömb előállítása az eredeti tömbből:

In [18]:
a<35 

array([ True,  True, False, False], dtype=bool)

"A" 2x2-es tömb létrehozása előredefiniált értékkel: 

In [19]:
A = np.array( [[1,1], 
              [0,1]] ) 

"B" 2x2-es tömb létrehozása:

In [20]:
B = np.array( [[2,0],
              [3,4]] ) 

A és B elemenkénti szorzása:

In [21]:
A*B 

array([[2, 0],
       [0, 4]])

A és B mátrixszorzása a numpy.dot() függvény segítségével. Mindkét sor ugyanazt csinálja.

In [22]:
np.dot(A, B) 
A.dot(B)

array([[5, 4],
       [3, 4]])

Csupa egyesekből álló álló "a" tömb létrehozása és "a" minden elemének megszorzása hárommal:

In [23]:
a = np.ones((2,3), dtype=int)
a
a *= 3                        
a

array([[3, 3, 3],
       [3, 3, 3]])

2x3-as mátrix létrehozása és feltöltése a [0.0, 1.0) tartományból véletlenszerűen. A két megközelítés ugyanazt csinálja.

In [24]:
b = np.random.random((2,3)) 
b

array([[ 0.18608807,  0.4787416 ,  0.18588402],
       [ 0.46479941,  0.81659402,  0.60281705]])

In [25]:
b = np.random.rand(2,3)
b

array([[ 0.99493244,  0.44154557,  0.39444205],
       [ 0.34422926,  0.37196918,  0.60083953]])

Így is hozzá lehet adni "b" elemeihez "a" tömb elemeit:

In [26]:
b += a 
b

array([[ 3.99493244,  3.44154557,  3.39444205],
       [ 3.34422926,  3.37196918,  3.60083953]])

# Unáris operátorok

3x4-es méretű tömb létrehozása és feltöltése a numpy.arange() függvénnyel:

In [27]:
b = np.arange(12).reshape(3,4) 
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

Oszlop- és sorösszegek kíszámítása:

In [28]:
b.sum(axis=0) 

array([12, 15, 18, 21])

In [29]:
b.sum(axis=1) 

array([ 6, 22, 38])

A tömbön belüli legkisebb értékkel rendelkező sor és oszlop:

In [30]:
b.min(axis=0) 

array([0, 1, 2, 3])

In [31]:
b.min(axis=1) 

array([0, 4, 8])

Oszloponkénti és soronkénti kumulált összegek:

In [32]:
b.cumsum(axis=0) 

array([[ 0,  1,  2,  3],
       [ 4,  6,  8, 10],
       [12, 15, 18, 21]])

In [33]:
b.cumsum(axis=1) 

array([[ 0,  1,  3,  6],
       [ 4,  9, 15, 22],
       [ 8, 17, 27, 38]])

# Indexálás

Első 10 nemnegatív egész szám köbe:

In [34]:
a = np.arange(10)**3 
a

array([  0,   1,   8,  27,  64, 125, 216, 343, 512, 729])

A tömbök számozása 0-tól indul. (A LUA-ban 1-től)

In [35]:
a[2]  

8

Tömbön belüli intervallum kijelölése. Az intervallum felső korlátja már nem kerül bele a kiválasztásba.

In [36]:
a[2:5] 

array([ 8, 27, 64])

Az első elemtől a hatodikig, minden második elemhez 1000-res értéket ad:

In [37]:
a[:6:2] = 1000 
a

array([1000,    1, 1000,   27, 1000,  125,  216,  343,  512,  729])

Sorvektor megfordítása:

In [38]:
a[ : :-1] 

array([ 729,  512,  343,  216,  125, 1000,   27, 1000,    1, 1000])

5x4-es mátrix létrehozása:

In [39]:
b = np.arange(20).reshape(5,4) 
b

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11],
       [12, 13, 14, 15],
       [16, 17, 18, 19]])

Mind az oszlopok, mind a sorok indexe 0-tól kezdődik:

In [40]:
b[2,3] 

11

A második oszlop első öt darab eleme:

In [41]:
b[0:5, 1] 

array([ 1,  5,  9, 13, 17])

"b" tömb utolsó sora:

In [42]:
b[-1] 

array([16, 17, 18, 19])

# A Numpy tömb formájának manipulálás

3x4-es mátrix létrehozása és feltöltése random elemekkel:

In [43]:
a = np.floor(10*np.random.random((3,4))) 
a

array([[ 8.,  7.,  4.,  2.],
       [ 3.,  0.,  1.,  1.],
       [ 9.,  1.,  6.,  0.]])

Az eredeti 3x4-es mátrix átalakítása sorvektorrá a numpy.reshape() paranccsal:

In [44]:
a.reshape(1,12) 

array([[ 8.,  7.,  4.,  2.,  3.,  0.,  1.,  1.,  9.,  1.,  6.,  0.]])

 A numpy.shape() is használható, amennyiben nem változik meg az elemek száma az átalakítással:

In [45]:
a.shape = (6, 2) 
a

array([[ 8.,  7.],
       [ 4.,  2.],
       [ 3.,  0.],
       [ 1.,  1.],
       [ 9.,  1.],
       [ 6.,  0.]])

A mátrix transzponáltja. Csak egy és kétdimenziós esetekben használható:

In [46]:
a.T 

array([[ 8.,  4.,  3.,  1.,  9.,  6.],
       [ 7.,  2.,  0.,  1.,  1.,  0.]])

Megadhatjuk, hogy hány sort szeretnénk látni, az oszlopok számát pedig automatikusan kiszámolja:

In [47]:
a.reshape(3,-1) 

array([[ 8.,  7.,  4.,  2.],
       [ 3.,  0.,  1.,  1.],
       [ 9.,  1.,  6.,  0.]])

# Mátrixok összevonása

2 darab 2x2-es tömb létrehozása random elemekkel. Numpy.floor() alsó egészrész értékre alakítja:

In [48]:
a = np.floor(10*np.random.random((2,2))) 
a

array([[ 1.,  4.],
       [ 7.,  2.]])

In [49]:
b = np.floor(10*np.random.random((2,2))) 
b

array([[ 1.,  4.],
       [ 2.,  5.]])

A két tömb illesztése az 1. (vertikális) és a 2. (horizontális) dimenzió mentén:

In [50]:
np.concatenate((a, b), axis=0 ) 

array([[ 1.,  4.],
       [ 7.,  2.],
       [ 1.,  4.],
       [ 2.,  5.]])

In [51]:
np.concatenate((a, b), axis=1 ) 

array([[ 1.,  4.,  1.,  4.],
       [ 7.,  2.,  2.,  5.]])

# Mátrixok másolása

Az első 12 nemnegatív számból álló sorvektor létrehozása:

In [52]:
a = np.arange(12) 
a

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11])

"b" tömböt egyenlővé tesszük "a"-val:

In [53]:
b = a 

Egyenlőség vizsgálata:

In [54]:
b is a 

True

Ha b alakját megváltoztatom, akkor az a alakja is megváltozik:

In [55]:
b.shape = 3,4 
a.shape 

(3, 4)

Legyen "c" egy olyan tömb, amely ugyanúgy néz ki mint "a":

In [56]:
c = a.view() 
c is a 

False

A "c" tömbön keresztül látjuk az "a" tömb elemeit:

In [57]:
c.base is a 

True

Ha megváltoztatom a "c" tömb alakját, akkor az "a" tömb alakja nem változik:

In [58]:
c.shape = 2,6 
a.shape 

(3, 4)

Ha megváltoztatom "c" tömb negyedik elemét:

In [59]:
c[0,4] = 1234 
a

array([[   0,    1,    2,    3],
       [1234,    5,    6,    7],
       [   8,    9,   10,   11]])

Mély másolat (deep copy) készítése a tömbről, a "d" tömb nem "a"-ra hivatkozik, hanem független attól:

In [60]:
d = a.copy() 
d is a 

False

In [61]:
d.base is a 

False

# Garbage collector

A Python programozási nyelv rendelkezik memóriaszemét gyűjtéssel, mely segítségével elkerülhető a memóriaszivárgás. Mély neurális hálózatokban nagy adatmennyiséggel dolgozunk, ezért sok esetben szükséges lehet a memória "kézzel" történő ürítése, a Python ütemezése előtt. Ezt a következő képp tudjuk megtenni:

In [62]:
a = np.floor(10*np.random.random((3,4)))
a

array([[ 4.,  7.,  7.,  3.],
       [ 3.,  9.,  1.,  9.],
       [ 2.,  0.,  0.,  3.]])

In [63]:
a = []
a

[]

A Garbage Collector (GC) modul importálása és a teljes memóriaszemét gyűjtése. A gc.collect() visszatérési értéke a nem elért elemek száma.

In [64]:
import gc 
gc.collect()

9